language: python
python:
  - "3.3"
  - "2.7"

install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install numpy scipy
  - pip install -e .
  
script: 
  - PYTHONPATH=. py.test
