language: python
python:
  - "3.3"
  - "2.7"
  
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  
install:
  - conda update --yes conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy
  - source activate test-environment
  - python setup.py install
  
script: 
  - PYTHONPATH=. py.test
